# Generated by Django 3.2.6 on 2021-08-19 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdata',
            old_name='user',
            new_name='profile',
        ),
    ]
